project:
  type: website
  output-dir: docs

website:
  title: "Paulo Oyama"
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  page-footer:
    center: 
      - icon: github
        href: https://github.com/PauloOyama
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Portfolio"
        contents:
          - projects.qmd
          - section: "Monte Carlo"
            contents: 
              - Monte_Carlo_Pt1.qmd

  navbar:
    tools:
      #- icon: envelope
      #  href: papaloyama@gmail.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/PauloOyama/PauloOyama.github.io
          - text: Report a Bug
            url:  https://github.com/PauloOyama/PauloOyama.github.io/issues
    background: 'dark'
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - projects.qmd 

format:
  html:
    theme: 
      dark: darkly
      light: lux
    grid:
      sidebar-width: 150px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem

editor: visual

