project:
  type: website
  output-dir: docs


sidebar: false
code-block-border-left: "#334061"

website:
  page-navigation: true
  title: "Paulo Oyama"
  back-to-top-navigation: true
  page-footer:
    center: 
      - icon: github
        href: https://github.com/PauloOyama
  sidebar:
    - id: MonteCarlo
      contents:
        - portfolio/MonteCarlo/index.qmd          
        - section: 'Estudo'
          contents:
            - href: portfolio/MonteCarlo/Monte_Carlo_Pt1.qmd
            - href: portfolio/MonteCarlo/Monte_Carlo_Pt2.qmd

  navbar:
    tools:
      - icon: envelope
        href: mailto:papaloyama@gmail.com@gmail.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/PauloOyama/PauloOyama.github.io
          - text: Report a Bug
            url:  https://github.com/PauloOyama/PauloOyama.github.io/issues
    background: 'dark'
    right:
      - text: "Home"
        href: index.qmd
      - text: 'Portfolio'
        href: projects.qmd 

format:
  html:
    mainfont: "Tahoma"
    lang: pt
    code-overflow: scroll
    theme: 
      dark: darkly
      light: lux
    toc: true
    grid:
      sidebar-width: 150px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem

editor: visual

