project:
  type: website
  output-dir: docs

website:
  title: "Paulo Oyama"
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  page-footer:
    center: 
      - icon: github
        href: https://github.com/PauloOyama
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Layout"
        contents:
          - projects.qmd
  

  navbar:
    tools:
      #- icon: envelope
      #  href: papaloyama@gmail.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/PauloOyama/PauloOyama.github.io
          - text: Report a Bug
            url:  https://github.com/PauloOyama/PauloOyama.github.io/issues
    background: 'dark'
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - projects.qmd 

format:
  html:
    page-layout: full
    theme: 
      dark: darkly
      light: lux
    toc: true

editor: visual

